In [14]:
import pandas as pd
import re
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,precision_score,recall_score
from sklearn.model_selection import train_test_split
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
import numpy as np

In [15]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\vikas\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [16]:
df=pd.read_csv(r'C:\Users\vikas\Documents\My Projects dataset\archive.zip')

In [17]:
df.isnull().sum()

title              0
news_url         330
source_domain    330
tweet_num          0
real               0
dtype: int64

In [18]:
df.dropna(inplace=True)   # removing null value

In [19]:
df.isnull().sum()

title            0
news_url         0
source_domain    0
tweet_num        0
real             0
dtype: int64

In [20]:
df.head()

,title,news_url,source_domain,tweet_num,real
0,Kandi Burruss Explodes Over Rape Accusation on...,http://toofab.com/2017/05/08/real-housewives-a...,toofab.com,42,1
1,People's Choice Awards 2018: The best red carp...,https://www.today.com/style/see-people-s-choic...,www.today.com,0,1
2,Sophia Bush Sends Sweet Birthday Message to 'O...,https://www.etonline.com/news/220806_sophia_bu...,www.etonline.com,63,1
3,Colombian singer Maluma sparks rumours of inap...,https://www.dailymail.co.uk/news/article-33655...,www.dailymail.co.uk,20,1
4,Gossip Girl 10 Years Later: How Upper East Sid...,https://www.zerchoo.com/entertainment/gossip-g...,www.zerchoo.com,38,1


In [21]:
df.duplicated().sum()

136

In [22]:
df['content']= df['title']+ ' ' + df['source_domain']

In [23]:
x=df[['title','news_url','source_domain','tweet_num','content']]
y=df['real']

In [24]:
print(x)
print(y)

                                                   title  \
0      Kandi Burruss Explodes Over Rape Accusation on...   
1      People's Choice Awards 2018: The best red carp...   
2      Sophia Bush Sends Sweet Birthday Message to 'O...   
3      Colombian singer Maluma sparks rumours of inap...   
4      Gossip Girl 10 Years Later: How Upper East Sid...   
...                                                  ...   
23191  Pippa Middleton wedding: In case you missed it...   
23192  Zayn Malik & Gigi Hadid’s Shocking Split: Why ...   
23193  Jessica Chastain Recalls the Moment Her Mother...   
23194  Tristan Thompson Feels "Dumped" After Khloé Ka...   
23195  Kelly Clarkson Performs a Medley of Kendrick L...   

                                                news_url  \
0      http://toofab.com/2017/05/08/real-housewives-a...   
1      https://www.today.com/style/see-people-s-choic...   
2      https://www.etonline.com/news/220806_sophia_bu...   
3      https://www.dailymail.co.uk/news

In [25]:
port_stem=PorterStemmer()

In [35]:
def stemming(content):
    stemmed_content= re.sub('[^a-zA-Z]', ' ',content)
    stemmed_content= stemmed_content.lower()
    stemmed_content= stemmed_content.split()
    stemmed_content= [port_stem.stem(word) for word in stemmed_content if not word in stopwords.words('english')]
    stemmed_content= ' '.join(stemmed_content)
    return stemmed_content

In [36]:
df['content']= df['content'].apply(stemming)

In [37]:
print(df['content'])

0        kandi burruss explod rape accu real housew atl...
1        peopl choic award best red carpet look www tod...
2        sophia bush send sweet birthday messag one tre...
3        colombian singer maluma spark rumour inappropr...
4        gossip girl year later upper east sider shock ...
                               ...                        
23191    pippa middleton wed case miss pippa marri lace...
23192    zayn malik gigi hadid shock split chanc reunit...
23193    jessica chastain recal moment mother boyfriend...
23194    tristan thompson feel dump khlo kardashian ref...
23195    kelli clarkson perform medley kendrick lamar h...
Name: content, Length: 22866, dtype: object


In [38]:
x=df['content'].values
y=df['real'].values

print(x)

['kandi burruss explod rape accu real housew atlanta reunion video toofab com'
 'peopl choic award best red carpet look www today com'
 'sophia bush send sweet birthday messag one tree hill co star hilari burton breyton eva www etonlin com'
 ...
 'jessica chastain recal moment mother boyfriend slap kick genit www justjar com'
 'tristan thompson feel dump khlo kardashian refu let move la home exclu www intouchweekli com'
 'kelli clarkson perform medley kendrick lamar humbl hit billboard music award www billboard com']


In [39]:
print(y)

[1 1 1 ... 1 0 1]


In [ ]:
# to transform textual data in numeric value

In [42]:
vectorize= TfidfVectorizer()
vectorize.fit(x)
x= vectorize.transform(x) 

In [43]:
print(x)

  (0, 13523)	0.21097464686381776
  (0, 12829)	0.2946204587818103
  (0, 10438)	0.2544682187163919
  (0, 10152)	0.23126529964745074
  (0, 10100)	0.3021195356648424
  (0, 6566)	0.3876166852086369
  (0, 5819)	0.26112988906419365
  (0, 4140)	0.35512293803690465
  (0, 2433)	0.050307199032079884
  (0, 1689)	0.3876166852086369
  (0, 642)	0.307346670554337
  (0, 56)	0.25959055664185965
  (1, 14111)	0.10116940271106599
  (1, 12795)	0.36812990418126346
  (1, 10220)	0.3770049713980729
  (1, 9362)	0.23663319582040224
  (1, 7349)	0.3328556941372697
  (1, 2433)	0.0808218887102497
  (1, 2195)	0.42261323723812544
  (1, 1895)	0.3875185362186333
  (1, 1086)	0.3386349813549023
  (1, 719)	0.3087811557820365
  (2, 14111)	0.05397566574362842
  (2, 12965)	0.30438721304787675
  (2, 12236)	0.23293003934564366
  :	:
  (22864, 10263)	0.31889894011570913
  (22864, 8290)	0.282396765181539
  (22864, 7148)	0.3088097057104033
  (22864, 6912)	0.26372058206690074
  (22864, 6715)	0.2872100260776159
  (22864, 6579)	0.1750

In [46]:
x=x.toarray()   # to conver spars array in normal array
print(x)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [52]:
x_train,x_test,y_train,y_test= train_test_split(x,y, test_size=0.2, random_state=2)

In [ ]:
# trainng model on logistic regression  

In [53]:
logic_r= LogisticRegression()
logic_r.fit(x_train,y_train)
y_pred= logic_r.predict(x_test)

C:\ProgramData\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [54]:
print(y_pred)

[1 1 1 ... 0 1 1]


In [ ]:
#checking accuracy

In [55]:
accuracy=accuracy_score(y_pred,y_test)
print('accuracy is',accuracy)

accuracy is 0.8710100568430258


In [57]:
x_train_pred=logic_r.predict(x_train)
accuracy_t=accuracy_score(x_train_pred,y_train) 
print('accuracy is:',accuracy)

accuracy is: 0.8710100568430258


In [58]:
df.shape

(22866, 6)

In [78]:
# creating checking model

x_model= x_test[10].reshape(1,-1)              #to reshape data in (1,14271) form
y_model_predict= logic_r.predict(x_model)
print(y_model_predict)

if y_model_predict==0:
    print("news is fake")
    
else:
    print("news is real")

[1]
news is real


In [77]:
print(y_test[10])

1
